appname: "elegon"
entrypoints:
    web:
        cmd: "gunicorn -c gunicorn_config.py app:app"
        ports:
            - "5000/tcp"
    raw:
        cmd: "python app.py"
        ports:
            - "5000/tcp"
build: "pip install -r ./requirements.txt"
